version: '3'
services:
  app:
    build: .
    environment:
      DATABASE_URL: mysql2://root:pass@db:3306
    ports:
      - '3000:3000'
    volumes: 
      - .:/freelance-project-scraping
    # depends_on:
    #   - db
#   db:
#     image: mysql:5.7.25
#     environment: 
#       MYSQL_ROOT_PASSWORD: 'pass'
#     ports:
#       - '3306:3306'
#     volumes:
#       - mysql-data:/var/lib/mysql
# volumes:
#   mysql-data:
#     driver: local
